### PR TITLE
housekeeping: update coding template, test, reqs, copyright

### PR DESCRIPTION
**Pull request by tchklovski**
## Description
ClickUp [task](https://app.clickup.com/t/v9d0dq)

This PR add a test, adds this PR template, tweaks requirements.
All in all, a more ready-to-go template

This is a small change, very simple code.

The folliwing does not apply:
- [ ] This PR part of a larger effort
        - what will be addressed in separate PRs?
        - what documentation/testing is being delayed to another PR?
- [ ] Added TODO comments about: work not shipped in this PR
- [ ] Added TODO comments about: optimizations/refactoring

## Checklist
- [x] The PR has an informative **title**?
- [x] The branch to merge has your name in it, `your-name/more-about-change` ?
- [x] Updated README.md and inline documentation
- [x] New files have copyright statement at the top
- [x] All files have up to date description of what the file does
- [x] Followed the other [Coding standards](https://github.com/predictionmachine/pm-coding-template#code-contents)?
- [x] *labels* have been applied to the PR

### CODE REVIEW

**Comment by tchklovski** [comment]
Task linked: [CU-v9d0dq tweak CI](https://app.clickup.com/t/v9d0dq)

**Review by abhishekmishragithub — CHANGES_REQUESTED** [review]
The package removal from requirements.txt is breaking the CI build.
Can you please update the requirements.txt file in a separate PR along with ci.yml?

**Comment by tchklovski** [comment]
i see, yes reverting requirements.txt but will keep it in requirements-dev.txt as well. In a separate PR, we should switch in CI from pm-github-template (and modify it so it is not checking itself out for this repo)

**Comment by abhishekmishragithub** [comment]
> i see, yes reverting requirements.txt but will keep it in requirements-dev.txt as well. In a separate PR, we should switch in CI from pm-github-template (and modify it so it is not checking itself out for this repo)

Thanks. What's pm-github-template ? is it a repo?

**Review by abhishekmishragithub — APPROVED** [review]
LGTM 👍🏼 
🚀

**Comment by tchklovski** [comment]
> > i see, yes reverting requirements.txt but will keep it in requirements-dev.txt as well. In a separate PR, we should switch in CI from pm-github-template (and modify it so it is not checking itself out for this repo)
> 
> Thanks. What's pm-github-template ? is it a repo?
fixed -- I meant [pm-gh-actions](https://github.com/predictionmachine/pm-gh-actions)

**Pull request merged**
